# install http by using role concet
--- 
- name: install http using role
  hosts: localhost
  become: yes
  vars: 
    pkg: httpd
    svc: httpd
    file: /var/www/html/index.html
  tasks:
  - name: install httpd
    ansible.builtin.dnf:
      name: "{{pkg}}"
      state: present
  - name: start and enabl httpd
    ansible.builtin.systemd_service:
      name: "{{svc}}"
      state: started
      enabled: true
  - name: deploy index.html
    ansible.builtin.copy:
      src: index.html
      dest: "{{file}}"